### ISSUE TITLE
Don't remove /usr/include

### ISSUE THREAD

**Issue by AlexeyRaga** [mkaczanowski/docker-archlinux-arm#1]
Many go projects require some system *.h files that are located in `/usr/include`. 
Unfortunately, `Dockerfile` for `archlinux-golang` removes this folder :(

**Comment by mkaczanowski** [comment]
Hey @AlexeyRaga Thanks for notice. Working on it.

**Comment by mkaczanowski** [comment]
Fixed with commit:
https://github.com/mkaczanowski/docker-archlinux-arm/commit/f83db29035f12cc3a34991ed347474bdd634656c
