### ISSUE TITLE
Build nginx failing

### ISSUE THREAD

**Issue by purplefish32** [mkaczanowski/docker-archlinux-arm#2]
I am trying to install nginx via the ./build.sh command on a raspberry pi model B running the ARM version of Arch Linux, but I get the following error :

The command '/bin/sh -c pacman -Syu --noconfirm nginx; systemctl enable nginx' returned a non-zero code: 132

Sorry If this is a stupid issue, I am new to both Arch and Docker

**Comment by mkaczanowski** [comment]
How did you install docker on your raspberry pi?
